### ISSUE TITLE
Examples not working on macOS

### ISSUE THREAD

**Issue by ghztomash** [nannou-org/nannou#1029]
Following the [Getting Started](https://guide.nannou.cc/getting_started/running_examples) guide running the first example fails
```sh
cargo run --release --example draw
```
Fails with:
```sh
error: failed to run custom build command for `glsl-to-spirv v0.1.7`

Caused by:
  process didn't exit successfully: `/Users/tomash/Developer/Rust/nannou/target/release/build/glsl-to-spirv-a7106c869445878f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build/glslangValidator.exe
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/Users/tomash/Developer/Rust/nannou/target/release/build/glsl-to-spirv-9b50358e7dbe756b/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/Users/tomash/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/glsl-to-spirv-0.1.7/glslang" "-DCMAKE_OSX_ARCHITECTURES=arm64" "-DCMAKE_INSTALL_PREFIX=/Users/tomash/Developer/Rust/nannou/target/release/build/glsl-to-spirv-9b50358e7dbe756b/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- Configuring incomplete, errors occurred!

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
    Compatibility with CMake < 3.5 has been removed from CMake.

    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
    to tell CMake that the project requires at least <min> but has been updated
    to work with policies introduced by <max> or earlier.

    Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.



  thread 'main' panicked at /Users/tomash/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Platform:
```
Apple M1 Pro
macOS Sequoia 15.5 arm64
rustc 1.85.0 (4d91de4e4 2025-02-17)
cmake version 4.0.3
```

`cargo:rerun-if-changed=build/glslangValidator.exe` looks suspicious since I am on macOS
Also `glsl-to-spirv` appears to be a deprecated dependency.

Any ideas how to get anything running?

**Comment by ghztomash** [comment]
Interestingly enough, `generative_design` and `nature_of_code` examples run out of the box.

After some deeper investigation seems like there issue is with the `hotglsl` dependency.

Despite there being a few [newer commits](https://github.com/nannou-org/hotglsl/commits/master/), the dependency is [locked](https://github.com/nannou-org/nannou/blob/b670e7a385d658fde79c431366d7f629dc56655b/Cargo.lock#L2089) at `1c1a303`, which is before replacing `glsl-to-spirv` with `naga`.

Regenerating `Cargo.lock` and patching `nannou_isf/src/pipeline.rs` seems to solve the issue for me.

**Comment by ghztomash** [comment]
I see now this is already addressed by https://github.com/nannou-org/nannou/pull/988

**Comment by Boscop** [comment]
I'm also affected by this.
@mitchmindtree Can you please merge the PR #988 ? :)

**Comment by renaudfv** [comment]
Confirming this is still an issue and that PR [#988](https://github.com/nannou-org/nannou/pull/988) resolves it!

**Comment by CarltonS13** [comment]
For anyone else facing this issue before PR #988 gets merged, running `export CMAKE_POLICY_VERSION_MINIMUM=3.5` in the terminal before running the example worked for me.
