### ISSUE TITLE
Failure to compile on MacOS (metal crate)

### ISSUE THREAD

**Issue by bcongdon** [nannou-org/nannou#418]
Hi! I'm really excited to try out nannou. I'm having some issues compiling it on macOS 10.14.5. When I run `cargo run --release --example simple_draw` in the nannou repository, I'm getting an error compiling the `metal` crate.

I've tried compiling on both of these toolchains:
```
stable-x86_64-apple-darwin -- rustc 1.38.0 (625451e37 2019-09-23)
nightly-x86_64-apple-darwin -- rustc 1.40.0-nightly (c23a7aa77 2019-10-19)
```

On both toolchains, I get an error compiling the `metal` crate:

```
Compiling metal v0.13.1
error[E0282]: type annotations needed
   --> /Users/bencongdon/.cargo/registry/src/github.com-1ecc6299db9ec823/metal-0.13.1/src/lib.rs:128:13
    |
128 |             msg_send![self.0, release];
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ consider giving `result` a type
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

Here's the full error (though I don't think it yields much more information): https://pastebin.com/9YXijsjZ

Do you have any ideas of how I could fix this? Thanks! 😄

**Comment by mitchmindtree** [comment]
Thanks for the issue @bcongdon!

@JoshuaBatty @freesig are either of you on 10.14.5 and can try recreate this?

It looks like `vulkano-win` [uses the `metal` crate](https://github.com/vulkano-rs/vulkano/blob/master/vulkano-win/Cargo.toml#L19), but it seems master is using `0.17` whereas the version of vulkano used by nannou seems to use `0.13.1` judging by your error. I wonder if this has been addressed in one of the recent updates to vulkano's master branch.

@bcongdon could you try running the triangle example that's in the [vulkano repo](https://github.com/vulkano-rs/vulkano) on the master branch? If that works, then we likely just need to update our vulkano version, but this also means updating [conrod](https://github.com/pistondevelopers/conrod)'s vulkano version first.

**Comment by bcongdon** [comment]
Thanks for looking into this! Yup -- I was able to run the triangle example of vulkano 🙂

**Comment by bruceadams** [comment]
I see the same problem on macOS 10.15.

**Comment by invis87** [comment]
Same here, macOs 10.14.6
About vulkano's triangle example:
```
cargo run --bin triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/triangle`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LoadingError(LibraryLoadFailure("dlopen(libvulkan.1.dylib, 1): image not found"))', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by tallen11** [comment]
Anyone have a fix for this? On Catalina as well.

**Comment by mitchmindtree** [comment]
Just a heads up, fixing this within conrod and nannou relies on [the next version of vulkano getting published](https://github.com/vulkano-rs/vulkano/pull/1250) which is currently pending [winit 0.20 getting published](https://github.com/rust-windowing/winit/milestone/2).

If you have a project that depends on nannou, you may be able to work around this by patching the vulkano dependency with the master git branch. e.g. adding this to your toml:
```toml
[patch.crates-io]
vulkano = { git = "https://github.com/vulkano-rs/vulkano", branch = "master" }
```
If you're trying to run the nannou examples within the nannou repo itself, you will *also* need to change the existing `vulkano` entry under `[dependencies]` to:
```toml
#vulkano = "0.14"
vulkano = { git = "https://github.com/vulkano-rs/vulkano", branch = "master" }
```
You may be able to patch the `metal` dependency in a similar manner rather than patching `vulkano`, seeing as the `metal` crate is the culprit here. I'm not sure if these suggestions will cause other compiler errors as I don't have a macOS machine with me, but they could be worth a shot!

**Comment by bruceadams** [comment]
The patch does not work. My build still fails `Compiling metal v0.13.1`. I tried explicitly doing a patch for metal itself: no change. Reading the patch documentation, I'm not at all sure it will override a transitive dependency, which is what we want here.

**Comment by bruceadams** [comment]
Patch really does deal with transitive dependencies, but it demands that versions match. The master branch of vulkano-rs has`vulkano-win` at `0.15.0`, so the patch has no impact for dependencies that call for `vulkano-win` of `0.14.0`. Grabbing a checkout of vulkano and hacking it a bit, then this patch works in my little project

```toml
[patch.crates-io]
vulkano = { path = "../vulkano/vulkano" }
vulkano-win = { path = "../vulkano/vulkano-win" }
vulkano-shaders = { path = "../vulkano/vulkano-shaders" }
```

**Comment by AustinJ235** [comment]
``0.15`` was an accidental release. I don't have the power to yank packages. The errors defined here where the same the CI was outputting before I updated these deps.

@mitchmindtree If this is an issue that is impacting nannou I could release an alpha version of vulkano and it's packages or if you think going ahead with the release of ``0.16`` with winit alpha is alright. I don't know about the stability of the alpha version and how many breaking changes there will be before the official ``0.20``

**Comment by mitchmindtree** [comment]
@AustinJ235 is there any chance we could see vulkano 0.16 published that continues to depend on winit 0.19.4? Perhaps the recent commit that updates vulkano's winit dependency to 0.20 could be moved to another branch while we wait for a stable version of winit 0.20 to be published?

**Comment by AustinJ235** [comment]
@mitchmindtree All goes well with the CI I should have a vulkano release out today with winit 0.19. https://github.com/vulkano-rs/vulkano/pull/1267

**Comment by freesig** [comment]
Looking into this now 👀

**Comment by AustinJ235** [comment]
I'd suggest either running cargo update or deleting the Cargo.lock file. All versions should be up to date.

**Comment by mitchmindtree** [comment]
Thanks a lot @AustinJ235!

It looks like 0.16 of `vulkano` published successfully, though it seems `vulkano-shaders` and `vulkano-win` haven't yet been published?

Once they're published we can start the process of updating `conrod_vulkano`, `shade_runner` and `nannou` for this new version.

**Comment by edap** [comment]
Just to say that I have tested the push from yesterday and now it compiles. the example `simple_draw` it is a bit laggy, it does not update when the mouse move but just when I click. The example `2_2_forces_many` works smoothly. Thanks for the fix ;)

**Comment by mitchmindtree** [comment]
Hey folks! I have a nannou branch up now where this has been fixed. Josh's laptop secretly updated behind the scenes and so he ran into this today, we were able to confirm that this branch does fix the issue:
```toml
nannou = { git = "https://github.com/mitchmindtree/nannou", branch = "publish" }
```
Just waiting on `shade_runner` to get published then will merge and publish nannou 0.12 with the fix! Thanks everyone for reporting and sorry about the delay!

**Comment by flowb** [comment]
Hi,
I just tried downloading the repo onto my mac and running the draw example and I'm still getting this error. Maybe I'm doing something wrong?
Thanks

**Comment by edap** [comment]
I have just pulled from master, and actually I still have an error when trying to run "simple_draw". This time is cocoa complaining:

```
   --> /Users/da1/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.18.4/src/appkit.rs:544:9
    |
544 |         msg_send![self, releaseGlobally];
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |         |
    |         cannot infer type
    |         consider giving `result` a type
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by mitchmindtree** [comment]
Would you mind trying `cargo update`? It looks like `cocoa-0.18.4` has been pulled down, however the latest patch version is `cocoa-0.18.5` - running `cargo update` should automatically cause it to update that tiny patch version. Hopefully this fixes your issue!

**Comment by edap** [comment]
it worked ;)
